### ISSUE TITLE
ImportError: cannot import name 'BARF'

### ISSUE THREAD

**Issue by xiaokanghub** [SnowGirls/deflat#3]
Traceback (most recent call last):
  File "deflat/deflat.py", line 1, in <module>
    from barf.barf import BARF
  File "/Users/xkang/Envs/angr/lib/python3.6/site-packages/barf-0.5.0-py3.6.egg/barf/__init__.py", line 27, in <module>
    from barf import BARF
ImportError: cannot import name 'BARF'

**Comment by wxl2578163** [comment]
我也遇到这个问题，搜索路径没设置好，改一下导入方式：
from barf import BARF  => _from .barf import BARF_
import analysis   =>  _from .analysis import *_
